export const DISH_NAME = 'Type dish name'
export const DISH_NAME_PLACEHOLDER = 'e.g. Cake'
export const ADD_NEW_INGREDIENT = 'Add New Ingredient'
export const NAME = 'Name'
export const CHOOSE_SOME_INGREDIENTS = 'Ingredients'
export const UPLOAD_DISH_PHOTO = `You didn't choose any dish photo`
export const TYPE_DISH_NAME = `You didn't type dish name`
export const TYPE_DISH_DESCRIPTION = `You didn't type dish description`
export const APP_NAME = 'CookBook'
export const ADDRESS_NOT_FOUND = 'Address not found'
export const NOT_FOUND_REDIRECTING = 'Redirecting to Home Page for '
export const SECONDS = ' seconds.'
export const SEARCHBAR_PLACEHOLDER = 'Type some dish or ingredients'
export const ADDED_NEW_DISH = 'Added new dish'
export const ADD = 'Add'
export const CANCEL = 'Cancel'
export const CHOOSE_INGREDIENT_PLACEHOLDER = 'Choose some ingredients...'
export const CHOOSE_SOME_INGREDIENTS_ALERT = `You didn't choose dish ingredients`
export const DISH_DESCRIPTION = 'Dish description'